# Generated by Django 3.2.4 on 2021-06-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_category_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='test',
            new_name='text',
        ),
    ]
